spring:
  application:
    name: lemonade
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: macbook@pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
